### ISSUE TITLE
Tracker not on list?

### ISSUE THREAD

**Issue by interzone826** [ngosang/trackerslist#121] opened 2018-10-18 23:03 UTC
FYI,

My client is showing this tracker as "online":

udp://tracker.pirateparty.gr:6969/announce

Regards

**Comment by pahakalle** [comment] 2018-10-19 05:50
The tracker in question is a duplicate of udp://tracker.coppersurfer.tk:6969/announce, hence udp://tracker.pirateparty.gr:6969/announce is added to blacklist
https://github.com/ngosang/trackerslist/blob/a4c4ae20f2f3cd2dde08828d06d7bade0bc062f2/blacklist.txt#L114

**Closed** 2018-10-19 14:42 UTC
